"""Where and WHY were the M>2 cells in the pre-fix P5 medium solution?
(evidence behind the 2026-07-08 second re-diagnosis that closed the medium
gate — docs/roadmap.md P5, INVESTIGATION_kutta_closure.md. On a post-fix
cache the hot-cell audits report clean; the probe-sharing audit still shows
the recorded known-robustness item.)

This reads ONLY the local solution cache results/<level>_solution.npz
(gitignored, regenerated by run_demo.py when absent) + the mesh -- no solve,
seconds to run. Findings it reproduces (second re-diagnosis):

  * 18 of the 26 M>2 cells sit ON the wing at the outboard trailing edge
    (dist-to-wall ~ 0, x/c ~ 1.0-1.1, z/b ~ 0.80); only 8 are at the
    far-field sphere. The single M_max=5.20 cell IS far-field. Two MORE
    wing cells exceed the vacuum limit outright (q^2/q^2_vac 1.17/1.40,
    Mach undefined -- invisible to a plain M>2 count).
  * per-station Kutta audit: the mismatch is a SINGLE-STATION anomaly --
    every station has |F| <= 3.4e-3 except the one at z/b=0.801
    (F=+1.6e-2, |F|/Gamma = 37%, with a Gamma zigzag 0.063/0.043/0.062
    across its neighbors). The hot cells are the first layer of wake-seam
    cells of exactly that station band (st131-134).
  * probe-assignment degeneracy (M1 off-plane fallback): adjacent stations
    SHARE Kutta probe nodes (medium: 35 upper + 41 lower of 166 stations;
    the defect station shares its upper probe with its neighbor, and one
    pair has BOTH probes identical => two Gammas chase one reading). The
    independent per-station secant is ill-posed against that coupling.
  * floored cells are the DOWNSTREAM NEIGHBORS of the hot cells (own Mach
    0.7-1.5; they inherit a near-vacuum upstream rho) -- symptom, not cause.
    The upwind walk itself is healthy (no u(e)=e among the hot cells).
  * straddle census: NO tet anywhere contains both a master and a slave
    wake node (cut topology clean) -- rules out the "Gamma jump compressed
    into one P1 cell" hypothesis.
  * far-field cluster: the 8 cells hug the UNcut branch ray of the
    span-uniform 2D vortex (y=0+, x>x_v, z/b 1.0-1.15 BEYOND the tip,
    where no wake cut exists to carry the prescribed ~Gamma_mean jump)
    => far-field BC artifact, fixed by the spanwise Gamma(z) taper
    (constraints/dirichlet.py::farfield_dirichlet spanwise_gamma=True).
  * excluding the defect band + far-field, the whole remaining field is
    healthy (medium M_max 2.00 at the tip TE corner; coarse's global max
    1.470 is ALSO a TE seam cell, vs 1.396 in the supersonic pocket).

Usage:  python cases/demo/p5_onera_m6/diagnose_medium.py [coarse|medium]
Requires the .msh (regenerate via cases/meshes/onera_m6/generate_onera_m6.py)
and the local *_solution.npz cache. Cap threads: NUMBA_NUM_THREADS=16.
"""
import sys
from pathlib import Path

import numpy as np
from scipy.spatial import cKDTree

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from pyfp3d.constraints.wake import kutta_targets  # noqa: E402
from pyfp3d.kernels.upwind import UpwindOperator  # noqa: E402
from pyfp3d.mesh.reader import read_mesh  # noqa: E402
from pyfp3d.mesh.wake_cut import cut_wake  # noqa: E402
from pyfp3d.meshgen.wing3d import B_SEMI, MAC, chord_at, x_le  # noqa: E402
from pyfp3d.physics.isentropic import (  # noqa: E402
    GAMMA,
    density_field,
    limit_q2_field,
    mach_squared_field,
    q2_at_mach,
)
from pyfp3d.post.surface import _element_gradients_and_centroids  # noqa: E402

RES = Path(__file__).parent / "results"
M_INF = 0.84


def _tet_shape_quality(nodes, elements):
    """Normalized shape quality 6*sqrt(2)*V / l_rms^3 (=1 regular tet, ->0
    sliver) and a crude edge aspect ratio, per element."""
    p = nodes[elements]
    v = np.abs(np.einsum("ni,ni->n",
                         np.cross(p[:, 1] - p[:, 0], p[:, 2] - p[:, 0]),
                         p[:, 3] - p[:, 0])) / 6.0
    e = np.stack([p[:, i] - p[:, j] for i, j in
                  [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]], axis=1)
    el = np.linalg.norm(e, axis=2)
    q = 6.0 * np.sqrt(2.0) * v / (np.sqrt((el ** 2).mean(1)) ** 3 + 1e-300)
    return q, el.max(1) / np.maximum(el.min(1), 1e-30)


def diagnose(level: str):
    mesh = read_mesh(ROOT / f"cases/meshes/onera_m6/{level}.msh")
    mc, wc = cut_wake(mesh)
    d = np.load(RES / f"{level}_solution.npz")
    phi = d["phi"]
    gamma = d["gamma"]

    grad, cen = _element_gradients_and_centroids(mc.nodes, mc.elements, phi)
    q2 = np.sum(grad * grad, 1)
    mach = np.sqrt(np.maximum(mach_squared_field(q2, M_INF), 0.0))
    q, ar = _tet_shape_quality(mc.nodes, mc.elements)

    wall = np.unique(np.asarray(mc.boundary_faces["wall"], dtype=np.int64))
    ff = np.unique(np.asarray(mc.boundary_faces["farfield"], dtype=np.int64))
    d_wall = cKDTree(mc.nodes[wall]).query(cen)[0]
    d_ff = cKDTree(mc.nodes[ff]).query(cen)[0]
    zb = cen[:, 2] / B_SEMI
    xc = (cen[:, 0] - np.array([x_le(v) for v in cen[:, 2]])) / \
        np.array([chord_at(v) for v in cen[:, 2]])

    print(f"\n===== {level}: {len(mc.elements)} tets, M_max={mach.max():.3f} "
          f"(stored {np.sqrt(float(d['mach2_max'])):.3f}) =====")
    idx = np.where(mach > 2.0)[0]
    if len(idx) == 0:
        print(f"  no M>2 cells (mesh median shape quality {np.median(q):.2f})")
    else:
        on_wing = d_wall[idx] < 0.3 * MAC
        at_ff = d_ff[idx] < 0.5 * MAC
        print(f"  {len(idx)} cells M>2:  {on_wing.sum()} ON wing (dwall<0.3MAC), "
              f"{at_ff.sum()} at far-field sphere (dff<0.5MAC)")
        print(f"    on-wing:  x/c {xc[idx][on_wing].min():.2f}-{xc[idx][on_wing].max():.2f} "
              f"(TE if ~1), z/b {zb[idx][on_wing].min():.2f}-{zb[idx][on_wing].max():.2f}")
        print(f"    shape quality of M>2 cells: median {np.median(q[idx]):.2f} "
              f"min {q[idx].min():.2f} (mesh median {np.median(q):.2f}); "
              f"aspect ratio max {ar[idx].max():.1f}  => not slivers")
        e_hot = idx[np.argmax(mach[idx])]
        print(f"    M_max cell: M={mach[e_hot]:.2f} at "
              f"(x={cen[e_hot, 0]:.1f}, z/b={zb[e_hot]:.2f}), "
              f"dff={d_ff[e_hot]:.2f} => {'FAR-FIELD' if d_ff[e_hot] < 0.5 * MAC else 'wing'}")

    # spanwise Gamma roll-off (steepest |dGamma/dz| co-locates with the cluster)
    o = np.argsort(wc.station_z)
    zz, gg = wc.station_z[o], gamma[o]
    dg = np.gradient(gg, zz)
    k = np.argmax(-dg)
    print(f"  steepest spanwise Gamma roll-off at z/b={zz[k] / B_SEMI:.2f} "
          f"(dGamma/dz={dg[k]:.2f}); Gamma root {gg[0]:.3f} -> tip {gg[-1]:.4f}")

    # ---- [audit 1] floor/limit reproduction + attribution -------------
    q2l = limit_q2_field(q2, M_INF, 3.0, GAMMA)
    limited = q2l != q2
    rho = density_field(q2l, M_INF, GAMMA)
    upw = UpwindOperator(mc.nodes, mc.elements)
    rho_t = upw.rho_tilde(grad, q2l, rho, M_INF, 1.5, 0.95).copy()
    floored = rho_t == 0.05
    ust = upw._upstream.copy()
    print(f"  [floor/limit] floored={floored.sum()} (stored {int(d['n_floored'])}) "
          f"limited={limited.sum()} (stored {int(d['n_limited'])})")
    for name, mask in [("floored", floored), ("limited", limited)]:
        j = np.where(mask)[0]
        if len(j):
            print(f"    {name}: near-wall {int((d_wall[j] < 0.3 * MAC).sum())} "
                  f"/ far-field {int((d_ff[j] < 0.5 * MAC).sum())}; own M "
                  f"{np.round(mach[j], 2)} (floored cells inherit a near-vacuum "
                  f"upstream rho -- downstream symptom)")

    # vacuum-exceeding cells are invisible to a plain M>2 count
    vac = np.where(q2 > q2_at_mach(1e9, M_INF))[0]
    if len(vac):
        print(f"  [vacuum] {len(vac)} cells EXCEED the vacuum q2 limit: "
              + "; ".join(f"x/c={xc[e]:.2f} z/b={zb[e]:.2f} "
                          f"q2/q2vac={q2[e] / q2_at_mach(1e9, M_INF):.2f}"
                          for e in vac))

    # upstream-walk health of the hot wing cells
    wing_hot = idx[d_wall[idx] < 0.3 * MAC] if len(idx) else np.empty(0, int)
    if len(wing_hot):
        print(f"  [walk] u(e)==e among wing M>2 cells: "
              f"{int((ust[wing_hot] == wing_hot).sum())}/{len(wing_hot)} "
              f"(0 = upwind term never vanishes there; walk healthy)")

    # ---- [audit 2] per-station Kutta mismatch + probe sharing ---------
    F = kutta_targets(phi, wc) - gamma
    zzb = wc.station_z[o] / B_SEMI
    Fo = F[o]
    kbad = int(np.argmax(np.abs(Fo)))
    jbad = int(o[kbad])
    print(f"  [kutta] max|F|={np.abs(F).max():.3e} at z/b={zzb[kbad]:.3f} "
          f"(|F|/Gamma={abs(Fo[kbad]) / max(gamma[jbad], 1e-9):.1%}); "
          f"2nd largest {np.sort(np.abs(F))[-2]:.3e} -- single-station anomaly "
          f"if the gap is ~5x")
    n_sh = []
    for arr in (wc.kutta_upper, wc.kutta_lower):
        u, c_ = np.unique(arr, return_counts=True)
        n_sh.append(int((c_ > 1).sum()))
    both_same = 0
    for j in range(wc.n_stations):
        p = np.where(wc.te_station == j)[0]
        for j2 in range(j + 1, wc.n_stations):
            p2 = np.where(wc.te_station == j2)[0]
            if (set(wc.kutta_upper[p]) == set(wc.kutta_upper[p2])
                    and set(wc.kutta_lower[p]) == set(wc.kutta_lower[p2])):
                both_same += 1
    print(f"  [probes] shared across stations: {n_sh[0]} upper / {n_sh[1]} lower "
          f"nodes (of {wc.n_stations} stations); station pairs with BOTH probes "
          f"identical (two Gammas, one reading): {both_same}")

    # ---- [audit 3] straddle census (master+slave in one tet?) ---------
    mset = np.zeros(mc.nodes.shape[0], bool)
    mset[wc.master_nodes] = True
    sset = np.zeros(mc.nodes.shape[0], bool)
    sset[wc.slave_nodes] = True
    straddle = int((mset[mc.elements].any(1) & sset[mc.elements].any(1)).sum())
    print(f"  [straddle] tets containing both master+slave wake nodes: "
          f"{straddle} (0 = cut topology clean)")

    # ---- [audit 4] far-field branch-ray + clean-field M_max -----------
    farf = d_ff < 0.5 * MAC
    ff_hot = idx[~(d_wall[idx] < 0.3 * MAC)] if len(idx) else np.empty(0, int)
    if len(ff_hot):
        print(f"  [far-field] hot cells hug the UNcut branch ray: "
              f"y {np.round(cen[ff_hot, 1], 2)}, z/b {np.round(zb[ff_hot], 2)} "
              f"(beyond tip => no wake cut carries the prescribed jump; "
              f"Gamma_mean={gamma.mean():.4f})")
    band = (zb > 0.77) & (zb < 0.84) & (xc > 0.9)
    clean = ~band & ~farf
    print(f"  [clean field] M_max excluding defect band+far-field: "
          f"{mach[clean].max():.3f} (rest of the field healthy)")


if __name__ == "__main__":
    levels = sys.argv[1:] or ["coarse", "medium"]
    for lvl in levels:
        diagnose(lvl)
