"""V5 IBL-floor diagnosis (the GV5.1 follow-up) -- RECORDED diagnostic study.

Binding text: cases/analysis/v5_ibl_floor/PRE_REGISTRATION.md (committed at
53bf904 BEFORE the first execution, per discipline). Trigger: the GV5.1
band (b) HONEST FAIL -- the augmented Newton's blocker is the intrinsic
floor of the steady IBL residual on the cond(J_BL,BL) ~ 4e10 near-null
manifold. Diagnosis only: no closure/formulation edits, no solver changes,
no Newton retries.

States (regenerated by the committed GV5.1 recipe, never recomputed from
committed heavy artifacts):
  S1 = coarse loose-converged state (the amended GV5.1 seed; loose regen
       per ../v5_tight_coupling/run.py phase 1, wiring guard included)
  S2 = medium loose-converged state (same recipe; every S2 number carries
       the GV5.1 section-4 trajectory-scatter caveat)
  S3 = coarse k=1 state (tests/v5_state.py fixture; the Stage-3 smoke
       evidence baseline: cond ~ 4e10, 501/1236 sigma < 1e-6*max)

Operator: J_BL,BL = the U-U block of tight_driver.augmented_jacobian at
pack.x_base() (edge data frozen at pack base; splu-exact assembly,
FD-verified at 2e-8..5e-9 in GV5.1). Dense SVD at 1236^2/2460^2 is exact
to machine precision.

Questions Q1..Q7 and the artifact list are the pre-registered ones.
Verdict class: RECORDED (diagnostic; no pass/fail bands).

Run:  python cases/analysis/v5_ibl_floor/run.py
      python cases/analysis/v5_ibl_floor/run.py --states s1 s3
      python cases/analysis/v5_ibl_floor/run.py --phases q6 q7 --states s1
      (partial runs merge summary.csv by (question, states); the default
      full run regenerates every artifact from scratch)
"""

import argparse
import contextlib
import io
import importlib.util
import os
import re
import sys
import time

# resolve pyfp3d from THIS worktree (the site-packages editable install may
# point at a sibling worktree)
sys.path.insert(0, os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..")))

os.environ.setdefault("NUMBA_NUM_THREADS", "16")
os.environ.setdefault("OMP_NUM_THREADS", "16")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "16")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from pyfp3d.mesh.reader import read_mesh
from pyfp3d.mesh.wake_cut import cut_wake
from pyfp3d.viscous import closures as C
from pyfp3d.viscous import tight_driver as td
from pyfp3d.viscous.coupling import (
    CouplingConfig,
    build_airfoil_case,
    make_picard_lifting_driver,
    run_loose_coupling,
)
from pyfp3d.viscous.ibl3 import IBL3Solver
from tests.v5_state import (
    ALPHA,
    M_CAP,
    M_CRIT,
    M_INF,
    NACA_DIR,
    RE,
    RHO_FLOOR,
    UPWIND_C,
    build_k1_state,
    build_naca_case,
)

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
os.makedirs(RESULTS, exist_ok=True)

V3_RESULTS = os.path.join(HERE, "..", "v3_loose_coupling", "results")
GV51_RUN = os.path.join(HERE, "..", "v5_tight_coupling", "run.py")

# the closure state floors under diagnosis (Q4/Q6(b)); module constants
# baked into the @njit(cache=True) closures -- see the Q6(b) note in main
DELTA_MIN = C.DELTA_MIN    # 1.0e-8 thickness scale floor
RE_D_MIN = C.RE_D_MIN      # 1.0e-3 Re_delta floor

VAR_NAMES = ["delta", "A", "B", "Psi", "Ct1", "Ct2"]
N_NULL = 20                # Q2/Q5: the top-20 smallest-sigma vectors
SIG_RELS = (1.0e-6, 1.0e-8, 1.0e-10)   # Q1 near-null thresholds (x sigma_max)
RECIPE_TOL_K0 = 1e-8       # the GV5.1 wiring guard |dcl_k0|

SUMMARY = []               # (question, states, key_result, artifacts, verdict)


def _write_summary():
    """summary.csv: one row per (question, states), RECORDED. Merge-written
    after every record: fresh rows replace the same (question, states)
    pair, rows of phases not re-run are kept (the v5_tight_coupling
    _merge_tagged discipline) -- a late crash loses only the phases that
    did not complete."""
    rows = {}
    path = os.path.join(RESULTS, "summary.csv")
    if os.path.exists(path):
        with open(path) as f:
            lines = [ln.rstrip("\n") for ln in f if ln.strip()]
        for ln in lines[1:]:
            flds = ln.split(",", 2)
            if len(flds) >= 2:
                rows[(flds[0], flds[1])] = ln
    for t in SUMMARY:
        rows[(t[0], t[1])] = ",".join(str(x) for x in t)
    order = {f"Q{i}": i for i in range(1, 8)}
    out = sorted(rows.values(),
                 key=lambda ln: (order.get(ln.split(",", 1)[0], 99),
                                 ln.split(",", 2)[1]))
    _write_lines("summary.csv",
                 "question,states,key_result,artifacts,verdict", out)


def _record(question, states, key_result, artifacts):
    SUMMARY.append((question, states, key_result, artifacts, "RECORDED"))
    print(f"  [RECORDED] {question} {states}: {key_result}", flush=True)
    _write_summary()


def _write_lines(name, header, lines):
    path = os.path.join(RESULTS, name)
    with open(path, "w") as f:
        f.write(header + "\n")
        for ln in lines:
            f.write(ln + "\n")
    print(f"  wrote {path}", flush=True)


def _load_gv51_recipe():
    """build_loose_converged_state from the COMMITTED GV5.1 runner
    (../v5_tight_coupling/run.py) -- imported, not mirrored, so the seed
    construction cannot drift from the amended-protocol recipe."""
    spec = importlib.util.spec_from_file_location("gv51_run", GV51_RUN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build_loose_converged_state


# ---------------------------------------------------------------------------
# state construction (S1/S2 loose-converged, S3 k=1 fixture)
# ---------------------------------------------------------------------------


def build_loose_state(level):
    """S1/S2: the loose loop's converged state, regenerated with the
    committed GV3.1 recipe (../v5_tight_coupling/run.py phase 1, verbatim:
    picard driver, omega=1.0, n_outer_max=10, tol_ds=1e-3), wiring guard
    included (converged + |dcl_k0| <= 1e-8 vs the committed GV3.1 history,
    read -- never recomputed)."""
    import csv

    print(f"--- [{level}] loose-loop regeneration (committed GV3.1 recipe, "
          "the GV5.1 amended seed) ---", flush=True)
    mc, wc = cut_wake(read_mesh(os.path.join(NACA_DIR, f"{level}.msh")))
    cfg = CouplingConfig(re_chord=RE, m_inf=M_INF, alpha_deg=ALPHA)
    case = build_airfoil_case(
        mc.nodes, mc.elements, mc.boundary_faces["wall"], cfg)
    dz = float(np.ptp(mc.nodes[:, 2]))
    s_ref = 1.0 * dz

    from pyfp3d.post.surface import wall_force_coefficients

    def probe(phi, gamma, k):
        f = wall_force_coefficients(
            mc.nodes, mc.elements, mc.boundary_faces["wall"], phi,
            alpha_deg=ALPHA, s_ref=s_ref, m_inf=M_INF)
        return {"cl": f["cl"], "cd_p": f["cd_pressure"]}

    t0 = time.perf_counter()
    driver = make_picard_lifting_driver(mc, wc, M_INF, ALPHA)
    res = run_loose_coupling(driver, case, cfg, probe=probe)
    wall = time.perf_counter() - t0
    with open(os.path.join(V3_RESULTS, f"gv3_1_history_{level}.csv")) as f:
        loose_hist = list(csv.DictReader(f))
    d_k0 = abs(float(res.history[0]["cl"]) - float(loose_hist[0]["cl"]))
    guard_ok = bool(res.converged) and d_k0 <= RECIPE_TOL_K0
    print(f"    loose regen in {wall:.0f}s: converged={res.converged} "
          f"n_outer={res.n_outer} cl={float(res.history[-1]['cl']):.8f} "
          f"| wiring guard: dcl_k0={d_k0:.3e} (<= {RECIPE_TOL_K0:.0e}) "
          f"-> {'OK' if guard_ok else 'RECIPE ERROR'}", flush=True)
    if not guard_ok:
        raise RuntimeError(
            f"[{level}] loose-regen wiring guard failed (converged="
            f"{res.converged}, dcl_k0={d_k0:.3e}) -- recipe error, STOP")
    build_lc = _load_gv51_recipe()
    st = build_lc(mc, wc, cfg, case, res)
    st["loose_res"] = res
    st["level"] = level
    return st


def build_pack_and_svd(tag, st):
    """The tight pack at the state + the dense SVD of J_BL,BL at
    pack.x_base() (the pre-registered operator). Returns
    dict(tag, st, pack, J, U_svd, s, Vh)."""
    t0 = time.perf_counter()
    pack = td.build_tight_pack(st, UPWIND_C, M_CRIT, M_CAP, RHO_FLOOR)
    bl = td.augmented_jacobian_blocks(pack, pack.x_base())
    J = bl["J_blbl"].toarray()
    U_svd, s, Vh = np.linalg.svd(J)
    wall = time.perf_counter() - t0
    print(f"  [{tag}] pack + dense SVD of J_BL,BL ({J.shape[0]}^2) in "
          f"{wall:.0f}s: sigma_max={s[0]:.6e} sigma_min={s[-1]:.6e} "
          f"cond={s[0] / s[-1]:.3e}", flush=True)
    return {"tag": tag, "st": st, "pack": pack, "J": J,
            "U_svd": U_svd, "s": s, "Vh": Vh}


# ---------------------------------------------------------------------------
# shared node metadata / region labels
# ---------------------------------------------------------------------------


def node_meta(d):
    """Per-surface-node metadata: x/c, side (+1 upper / -1 lower), regime
    (laminar/turbulent/pin), region label, the closure-floor mirrors and
    the Q2 aggregate null energy (filled by q2 before q4)."""
    pack, st = d["pack"], d["st"]
    case = pack.case
    x_c = pack.sm.xyz[:, 0] / pack.cfg.chord
    side = np.asarray(case.stations.side_node, dtype=int)
    turb = np.asarray(case.turbulent_flags, dtype=int)
    inflow = np.asarray(st["inflow_mask"], dtype=bool)
    regime = np.where(inflow, "inflow_pin",
                      np.where(turb == 1, "turbulent", "laminar"))
    region = np.where(x_c <= pack.cfg.inflow_band_x, "le_inflow",
                      np.where(x_c <= pack.cfg.le_band_x, "le_band",
                               np.where(x_c >= 0.9, "te_band", "mid")))
    return {"x_c": x_c, "side": side, "turb": turb, "inflow": inflow,
            "regime": regime, "region": region}


def null_energy(d):
    """Q2: aggregate per-node energy of the top-N_NULL smallest-sigma
    RIGHT singular vectors (each vector's energy normalized to 1 first),
    plus the per-variable energy fractions (mean over the same vectors)."""
    n_s = d["pack"].n_s
    V = d["Vh"][-N_NULL:].T.reshape(n_s, 6, N_NULL)  # (node, var, rank)
    e_node = np.mean(np.sum(V ** 2, axis=1), axis=1)          # (node,)
    e_var = np.mean(np.sum(V ** 2, axis=0), axis=1)           # (6,)
    assert abs(float(np.sum(e_var)) - 1.0) < 1e-9, "e_var must sum to 1"
    return e_node, e_var


def _counts(s):
    """Near-null counts below the pre-registered relative thresholds."""
    return {f"{r:.0e}": int(np.sum(s < r * s[0])) for r in SIG_RELS}


# ---------------------------------------------------------------------------
# Q1 spectrum
# ---------------------------------------------------------------------------


def q1(states):
    print("=== Q1 spectrum of J_BL,BL (dense SVD) ===", flush=True)
    fig, ax = plt.subplots(figsize=(7, 5))
    for tag, d in states.items():
        s = d["s"]
        rel = s / s[0]
        _write_lines(
            f"spectrum_{tag}.csv", "idx,sigma,sigma_rel_max",
            [f"{i},{v:.16e},{r:.16e}" for i, (v, r) in enumerate(zip(s, rel))])
        cnt = _counts(s)
        # spectral gaps of the sorted spectrum: the three largest ratios
        gaps = s[:-1] / np.maximum(s[1:], 1e-300)
        top = np.argsort(gaps)[::-1][:3]
        gap_txt = "; ".join(f"gap@{i}->{i + 1}={gaps[i]:.2e}" for i in top)
        ax.semilogy(rel, label=f"{tag} (n={s.size})")
        _record(
            "Q1", tag,
            f"smax={s[0]:.4e} smin={s[-1]:.4e} cond={s[0] / s[-1]:.3e}; "
            f"near-null (<1e-6/1e-8/1e-10*smax): {cnt['1e-06']}/"
            f"{cnt['1e-08']}/{cnt['1e-10']} of {s.size}; top gaps: {gap_txt}",
            f"spectrum_{tag}.csv")
        d["q1"] = {"cond": s[0] / s[-1], "counts": cnt}
    for r in SIG_RELS:
        ax.axhline(r, color="gray", ls=":", lw=0.8)
        ax.text(0, r * 1.3, f"1e{int(np.log10(r))}", fontsize=8, color="gray")
    ax.set_xlabel("singular index")
    ax.set_ylabel(r"$\sigma / \sigma_{\max}$")
    ax.set_title(r"Q1: $\sigma(J_{BL,BL})$ dense SVD at S1/S2/S3")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(RESULTS, "spectrum.png"), dpi=150)
    plt.close(fig)
    print("  wrote spectrum.png", flush=True)


# ---------------------------------------------------------------------------
# Q2 null-space anatomy
# ---------------------------------------------------------------------------


def q2(tag, d):
    print(f"=== Q2 null-space anatomy [{tag}] (top {N_NULL} right "
          "singular vectors) ===", flush=True)
    meta = node_meta(d)
    e_node, e_var = null_energy(d)
    d["e_node_null"] = e_node
    lines = []
    for k, name in enumerate(VAR_NAMES):
        lines.append(f"variable,{name},,,,,{e_var[k]:.8e}")
    for i in range(d["pack"].n_s):
        lines.append(
            f"node,{i},{meta['x_c'][i]:.6f},{meta['side'][i]:d},"
            f"{meta['regime'][i]},{meta['region'][i]},{e_node[i]:.8e}")
    _write_lines(
        f"nullspace_anatomy_{tag}.csv",
        "section,name_or_node,x_c,side,regime,region,energy_fraction", lines)

    # localization: energy mass in the top-10 nodes and per region
    order = np.argsort(e_node)[::-1]
    top10 = float(np.sum(e_node[order[:10]]))
    reg_mass = {}
    for r in ("le_inflow", "le_band", "mid", "te_band"):
        reg_mass[r] = float(np.sum(e_node[meta["region"] == r]))
    top_txt = "; ".join(
        f"node{i}(x/c={meta['x_c'][i]:.3f},{'up' if meta['side'][i] > 0 else 'lo'},{meta['regime'][i]})"
        for i in order[:5])
    _record(
        "Q2", tag,
        f"var fractions: " + " ".join(
            f"{n}={v:.3f}" for n, v in zip(VAR_NAMES, e_var)) +
        f"; top-10-node mass={top10:.3f}; region mass: " +
        " ".join(f"{r}={v:.3f}" for r, v in reg_mass.items()) +
        f"; top nodes: {top_txt}",
        f"nullspace_anatomy_{tag}.csv")

    # strip map PNG: per-node aggregate energy vs x/c per side + var bars
    fig, (a0, a1) = plt.subplots(
        2, 1, figsize=(8, 7), gridspec_kw={"height_ratios": [3, 1]})
    for sv, name, mk in ((1, "upper", "o"), (-1, "lower", "s")):
        m = meta["side"] == sv
        a0.semilogy(meta["x_c"][m], e_node[m], mk, ms=3, alpha=0.6,
                    label=name)
    for x, lab in ((d["pack"].cfg.inflow_band_x, "inflow"),
                   (d["pack"].cfg.le_band_x, "le/x_tr"), (0.9, "TE band")):
        a0.axvline(x, color="gray", ls=":", lw=0.8)
        a0.text(x, a0.get_ylim()[1], lab, fontsize=8, color="gray")
    a0.set_xlabel("x/c")
    a0.set_ylabel("null-space energy (mean over top 20)")
    a0.set_title(f"Q2 null-space anatomy [{tag}]")
    a0.legend()
    a1.bar(VAR_NAMES, e_var)
    a1.set_ylabel("energy fraction")
    fig.tight_layout()
    fig.savefig(os.path.join(RESULTS, f"nullspace_map_{tag}.png"), dpi=150)
    plt.close(fig)
    print(f"  wrote nullspace_map_{tag}.png", flush=True)


# ---------------------------------------------------------------------------
# Q3 scaling discrimination
# ---------------------------------------------------------------------------


def q3(states):
    print("=== Q3 row/column equilibration: scaling artifact vs true "
          "rank deficiency ===", flush=True)
    lines = []
    for tag, d in states.items():
        J = d["J"]
        s0 = d["s"]
        rn = np.linalg.norm(J, axis=1)
        J1 = J * (1.0 / np.maximum(rn, 1e-300))[:, None]
        cn = np.linalg.norm(J1, axis=0)
        J2 = J1 * (1.0 / np.maximum(cn, 1e-300))[None, :]
        s1v = np.linalg.svd(J2, compute_uv=False)
        c0 = _counts(s0)
        c1 = _counts(s1v)
        lines.append(",".join([
            tag, f"{s0[0] / s0[-1]:.6e}", f"{s1v[0] / s1v[-1]:.6e}",
            f"{rn.max() / rn.min():.6e}", f"{cn.max() / cn.min():.6e}",
            str(c0["1e-06"]), str(c1["1e-06"]),
            str(c0["1e-08"]), str(c1["1e-08"]),
            str(c0["1e-10"]), str(c1["1e-10"])]))
        _record(
            "Q3", tag,
            f"cond raw={s0[0] / s0[-1]:.3e} -> equilibrated="
            f"{s1v[0] / s1v[-1]:.3e}; row-norm range={rn.max() / rn.min():.2e}"
            f" col-norm range={cn.max() / cn.min():.2e}; near-null "
            f"(<1e-6*smax) raw={c0['1e-06']} -> scaled={c1['1e-06']}",
            "scaling.csv")
    _write_lines(
        "scaling.csv",
        "state,cond_raw,cond_equilibrated,row_norm_range,col_norm_range,"
        "n_lt_1e-6_raw,n_lt_1e-6_scaled,n_lt_1e-8_raw,n_lt_1e-8_scaled,"
        "n_lt_1e-10_raw,n_lt_1e-10_scaled", lines)


# ---------------------------------------------------------------------------
# Q4 closure-floor active set (S1/S2)
# ---------------------------------------------------------------------------


def q4(tag, d):
    """Active set of the closures.py state floors, mirrored exactly from
    closure_node (closures.py:490-507): DELTA_MIN active iff delta <
    1e-8; re_d = rho*q*max(delta, DELTA_MIN)/mu; RE_D_MIN active iff
    re_d < 1e-3. Edge data = the pack base (the pre-registered frozen
    semantics, pack.q0/rho_e0/mu). The remaining min/max clamps in
    closures.py are division guards (1e-30/1e-12 magnitudes, never active
    at a physical state) plus the inner ctau-solve step clamp (not a
    state map) -- noted, not active-set material."""
    print(f"=== Q4 closure-floor active set [{tag}] ===", flush=True)
    pack = d["pack"]
    meta = node_meta(d)
    U = pack.U0
    delta = U[:, 0]
    delta_f = np.maximum(delta, DELTA_MIN)
    re_d = pack.rho_e0 * pack.q0 * delta_f / pack.mu
    a_d = delta < DELTA_MIN
    a_r = re_d < RE_D_MIN
    e_null = d.get("e_node_null", np.zeros(pack.n_s))
    lines = []
    for i in range(pack.n_s):
        if a_d[i] or a_r[i]:
            lines.append(",".join([
                str(i), f"{meta['x_c'][i]:.6f}", f"{meta['side'][i]:d}",
                meta["regime"][i], meta["region"][i],
                f"{delta[i]:.6e}", f"{re_d[i]:.6e}",
                str(bool(a_d[i])), str(bool(a_r[i])),
                f"{e_null[i]:.8e}"]))
    _write_lines(
        f"closure_floor_active_{tag}.csv",
        "node,x_c,side,regime,region,delta,re_d,delta_min_active,"
        "re_d_min_active,null_energy", lines)
    # overlap with the Q2 null support (vacuous when the set is empty)
    n_act = int(np.sum(a_d | a_r))
    if n_act:
        mass = float(np.sum(e_null[a_d | a_r]))
        overlap = f"null-energy mass on active nodes={mass:.4f}"
    else:
        overlap = ("active set EMPTY -> floor-active exact-null-direction "
                   "hypothesis not operative at this state; the DELTA_MIN "
                   "sensitivity is identically zero here (Q6(b) substitute)")
    _record(
        "Q4", tag,
        f"DELTA_MIN-active={int(np.sum(a_d))} RE_D_MIN-active="
        f"{int(np.sum(a_r))} of {pack.n_s} nodes "
        f"(min delta={delta.min():.3e} min re_d={re_d.min():.3e}); "
        + overlap,
        f"closure_floor_active_{tag}.csv")


# ---------------------------------------------------------------------------
# Q5 residual anatomy at the floor (S1/S2)
# ---------------------------------------------------------------------------


def q5(tag, d):
    print(f"=== Q5 residual anatomy at the floor [{tag}] ===", flush=True)
    pack = d["pack"]
    meta = node_meta(d)
    F = td.block_residuals(pack, pack.x_base())[2].reshape(pack.n_s, 6)
    fmax = np.max(np.abs(F), axis=1)
    lines = []
    for i in range(pack.n_s):
        lines.append(",".join(
            [str(i), f"{meta['x_c'][i]:.6f}", f"{meta['side'][i]:d}",
             meta["regime"][i], meta["region"][i]]
            + [f"{F[i, k]:.6e}" for k in range(6)]
            + [f"{fmax[i]:.6e}"]))
    _write_lines(
        f"residual_anatomy_{tag}.csv",
        "node,x_c,side,regime,region,F_delta,F_A,F_B,F_Psi,F_Ct1,F_Ct2,"
        "F_max", lines)

    # alignment with the LEFT singular vectors across the spectrum
    Ff = F.ravel()
    nrm = float(np.linalg.norm(Ff))
    align = np.abs(d["U_svd"].T @ Ff) / max(nrm, 1e-300)
    _write_lines(
        f"residual_alignment_{tag}.csv",
        "idx,sigma_rel_max,abs_align_over_Fnorm",
        [f"{i},{d['s'][i] / d['s'][0]:.16e},{align[i]:.8e}"
         for i in range(align.size)])
    eq_tot = np.linalg.norm(F, axis=0) / max(nrm, 1e-300)
    order = np.argsort(fmax)[::-1]
    top_txt = "; ".join(
        f"node{i}(x/c={meta['x_c'][i]:.3f},{'up' if meta['side'][i] > 0 else 'lo'},"
        f"{meta['regime'][i]},|F|={fmax[i]:.2e})" for i in order[:5])
    ali_null = align[-N_NULL:]
    _record(
        "Q5", tag,
        f"|F_BL|inf={fmax.max():.4e}; eq energy shares: " +
        " ".join(f"{n}={v:.3f}" for n, v in zip(VAR_NAMES, eq_tot)) +
        f"; top nodes: {top_txt}; |u_i^T F|/|F| over the {N_NULL} "
        f"smallest-sigma left vectors: max={ali_null.max():.3e} "
        f"median={np.median(ali_null):.3e} (random ~ "
        f"{1.0 / np.sqrt(Ff.size):.2e})",
        f"residual_anatomy_{tag}.csv")
    return align


def q5_pngs(figs):
    """One combined residual_alignment.png (S1/S2 overlaid)."""
    fig, ax = plt.subplots(figsize=(7, 5))
    for tag, (align, s) in figs.items():
        ax.loglog(s / s[0], np.maximum(align, 1e-16), ".", ms=3,
                  label=tag, alpha=0.6)
        ax.axhline(1.0 / np.sqrt(s.size), color="gray", ls=":", lw=0.8)
    ax.invert_xaxis()
    ax.set_xlabel(r"$\sigma_i / \sigma_{\max}$")
    ax.set_ylabel(r"$|u_i^T F_{BL}| / |F_{BL}|_2$")
    ax.set_title("Q5 residual alignment with left singular vectors "
                 "(dotted: random ~1/sqrt(6n))")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(RESULTS, "residual_alignment.png"), dpi=150)
    plt.close(fig)
    print("  wrote residual_alignment.png", flush=True)


# ---------------------------------------------------------------------------
# Q6 formulation sensitivity probes (coarse, S1 only)
# ---------------------------------------------------------------------------


def _resolve_with_eps(st, f_eps, f_eps_s, U0):
    """A fresh IBL3Solver identical to the S1 one except the artificial
    diffusion coefficients (the pre-registered Q6(a) interface probe --
    eps_diff/eps_diff_s are constructor kwargs, ibl3.py:1182-1184),
    solved from the SAME seed U0 = S1's U."""
    cfg = st["cfg"]
    solver = IBL3Solver(
        st["sm"], st["ue_surf"], st["rho_e"], st["mu"], st["mach_e"],
        st["case"].turbulent_flags, st["inflow_mask"], st["inflow_state"],
        eps_diff=cfg.eps_diff * f_eps, eps_diff_s=cfg.eps_diff_s * f_eps_s)
    U, info = solver.solve(U0, tol=cfg.ibl_tol, max_iter=cfg.ibl_max_iter)
    _, J = solver.residual_jacobian(U)
    s = np.linalg.svd(J.toarray(), compute_uv=False)
    return U, info, s


def q6(d, base):
    print("=== Q6 formulation sensitivity probes [s1] ===", flush=True)
    st = d["st"]
    cfg = st["cfg"]
    U0 = np.ascontiguousarray(st["U"], dtype=np.float64)
    base_U, base_info, base_s = base
    base_floor = base_info["final_residual"]
    base_cnt = _counts(base_s)
    lines = [",".join([
        "eps_base(x1)", "1.0", "1.0", f"{cfg.eps_diff:.4g}",
        f"{cfg.eps_diff_s:.4g}", str(base_info["converged"]),
        str(base_info["n_iter"]), f"{base_floor:.6e}", "1.0",
        str(base_cnt["1e-06"]), str(base_cnt["1e-08"]),
        f"{base_s[0] / base_s[-1]:.6e}",
        "re-solve from S1 U at the pack eps (the Q7 run)"])]
    for f_e, f_es, lab in ((0.5, 1.0, "eps_diff x0.5"),
                           (2.0, 1.0, "eps_diff x2"),
                           (0.5, 0.5, "both x0.5 (extra)"),
                           (2.0, 2.0, "both x2 (extra)")):
        t0 = time.perf_counter()
        _, info, s = _resolve_with_eps(st, f_e, f_es, U0)
        cnt = _counts(s)
        wall = time.perf_counter() - t0
        lines.append(",".join([
            lab, f"{f_e:.2f}", f"{f_es:.2f}",
            f"{cfg.eps_diff * f_e:.4g}", f"{cfg.eps_diff_s * f_es:.4g}",
            str(info["converged"]), str(info["n_iter"]),
            f"{info['final_residual']:.6e}",
            f"{info['final_residual'] / base_floor:.4f}",
            str(cnt["1e-06"]), str(cnt["1e-08"]),
            f"{s[0] / s[-1]:.6e}", f"wall={wall:.0f}s"]))
        print(f"  Q6 {lab}: converged={info['converged']} "
              f"n_iter={info['n_iter']} floor={info['final_residual']:.3e} "
              f"(x{info['final_residual'] / base_floor:.3f} vs base) "
              f"near-null(1e-6)={cnt['1e-06']} ({wall:.0f}s)", flush=True)
    # Q6(b): DELTA_MIN probe -- DEFERRED per the pre-registration fallback
    # clause + the 2026-07-24 user instruction ("no hard source edits"):
    # DELTA_MIN/RE_D_MIN are module constants baked into the
    # @njit(cache=True) closures (closures.py:77-78, consumed inside
    # closure_node at :490-507); they are exposed through NEITHER the
    # closure_all signature NOR the IBL3Solver constructor, and numba
    # freezes globals at compile time, so the pre-registered "logged
    # local edit reverted in the same run" would silently no-op against
    # the cached compilation (an unclean probe). Substitute evidence:
    # the Q4 active set (if empty, the DELTA_MIN sensitivity is
    # identically zero at S1 by construction).
    lines.append(",".join([
        "DELTA_MIN probe", "", "", "", "", "", "", "", "", "", "", "",
        "DEFERRED (not cleanly probeable via the interface; numba-baked "
        "module constant; Q4 active set is the substitute evidence)"]))
    _write_lines(
        "sensitivity_probes.csv",
        "probe,factor_eps_diff,factor_eps_diff_s,eps_diff,eps_diff_s,"
        "converged,n_iter,final_residual,floor_ratio_vs_base,"
        "n_sigma_lt_1e-6,n_sigma_lt_1e-8,cond,note", lines)
    _record("Q6", "s1",
            f"(a) eps_diff probes done (see sensitivity_probes.csv; base "
            f"floor={base_floor:.3e} near-null(1e-6)={base_cnt['1e-06']}); "
            "(b) DELTA_MIN DEFERRED -- numba-baked module constant with no "
            "interface exposure; Q4 active set substitutes",
            "sensitivity_probes.csv")


# ---------------------------------------------------------------------------
# Q7 pseudo-time stall anatomy (coarse, S1 only)
# ---------------------------------------------------------------------------


def q7(d):
    print("=== Q7 pseudo-time stall anatomy [s1] (standalone IBL3Solver "
          "from S1, verbose controller trace) ===", flush=True)
    st = d["st"]
    cfg = st["cfg"]
    solver = st["solver"]
    U0 = np.ascontiguousarray(st["U"], dtype=np.float64)
    buf = io.StringIO()
    t0 = time.perf_counter()
    with contextlib.redirect_stdout(buf):
        U, info = solver.solve(U0, tol=cfg.ibl_tol,
                               max_iter=cfg.ibl_max_iter, verbose=True)
    wall = time.perf_counter() - t0
    lines, events = [], []
    cur_it = None
    for ln in buf.getvalue().splitlines():
        m = re.match(r"\[ibl3\] it=(\d+) cfl=([\d.eE+-]+) \|R\|inf="
                     r"([\d.eE+-]+)", ln)
        if m:
            cur_it = int(m.group(1))
            events.append(("iter", cur_it, float(m.group(2)),
                           float(m.group(3))))
        elif "step rejected" in ln:
            m2 = re.search(r"cfl <- ([\d.eE+-]+)", ln)
            events.append(("reject", cur_it, float(m2.group(1)), ""))
    for kind, it, cfl, r in events:
        lines.append(f"{kind},{it},{cfl:.6e},{r if r == '' else f'{r:.6e}'}")
    hist = info["residual_history"]
    lines.append(",".join([
        "final", str(info["n_iter"]), f"{info['cfl_final']:.6e}",
        f"{info['final_residual']:.6e}"]))
    _write_lines("pseudotime_stall.csv", "record,iter,cfl,r_inf", lines)
    n_rej = sum(1 for k, *_ in events if k == "reject")
    cfl_min = 1.0e-3  # cfl0 (=1.0) * 1e-3, ibl3.py:1476
    plateau = (hist[-1] / hist[0]) if hist and hist[0] > 0 else float("nan")
    tail = (f"last 10 iters: {hist[-10]:.3e} -> {hist[-1]:.3e}"
            if len(hist) >= 10 else "n/a")
    bottomed = info["cfl_final"] <= 1.5 * cfl_min and n_rej > 0
    _record(
        "Q7", "s1",
        f"converged={info['converged']} n_iter={info['n_iter']} "
        f"rejections={n_rej} cfl_final={info['cfl_final']:.3e} "
        f"(cfl_min={cfl_min:.0e}); r_inf {hist[0]:.3e} -> "
        f"{hist[-1]:.3e} (ratio {plateau:.4f}); {tail}; "
        f"{'controller BOTTOMED OUT (cfl pinned at cfl_min; steps rejected; residual frozen at the floor)' if bottomed else 'residual plateaus at FULL step (formulation floor signature)'}; "
        f"wall={wall:.0f}s",
        "pseudotime_stall.csv")
    return U, info, np.linalg.svd(
        solver.residual_jacobian(U)[1].toarray(), compute_uv=False)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--states", nargs="+", default=["s1", "s2", "s3"],
                    choices=["s1", "s2", "s3"],
                    help="states to diagnose (default: all three)")
    ap.add_argument("--phases", nargs="+",
                    default=["q1", "q2", "q3", "q4", "q5", "q6", "q7"],
                    choices=["q1", "q2", "q3", "q4", "q5", "q6", "q7"],
                    help="questions to run (default: all; q6 implies q7 -- "
                         "the Q6 base re-solve IS the Q7 run). Partial "
                         "runs merge summary.csv rows by (question, "
                         "states); the default full run regenerates "
                         "every artifact from scratch.")
    args = ap.parse_args()
    t_all = time.perf_counter()
    phases = set(args.phases)
    if "q6" in phases:
        phases.add("q7")

    states = {}
    if "s3" in args.states:
        print("=== S3: coarse k=1 fixture (tests/v5_state.py) ===",
              flush=True)
        states["s3"] = build_pack_and_svd("s3", build_k1_state(
            build_naca_case()))
    if "s1" in args.states:
        print("=== S1: coarse loose-converged state ===", flush=True)
        states["s1"] = build_pack_and_svd("s1", build_loose_state("coarse"))
    if "s2" in args.states:
        print("=== S2: medium loose-converged state (GV5.1 section-4 "
              "trajectory-scatter caveat on every number) ===", flush=True)
        states["s2"] = build_pack_and_svd("s2", build_loose_state("medium"))

    if "q1" in phases:
        q1(states)

    # Q2 at S1 always; at S2 iff the near-null cluster persists (Q1)
    if "q2" in phases:
        if "s1" in states:
            q2("s1", states["s1"])
        if "s2" in states:
            cnt_s2 = _counts(states["s2"]["s"])["1e-06"]
            persist = cnt_s2 >= N_NULL
            print(f"  Q2[s2]: near-null cluster persists at S2 = "
                  f"{persist} (count(1e-6)={cnt_s2})", flush=True)
            if persist:
                q2("s2", states["s2"])

    if "q3" in phases:
        q3(states)

    if "q4" in phases:
        for tag in ("s1", "s2"):
            if tag in states:
                q4(tag, states[tag])

    if "q5" in phases:
        figs = {}
        for tag in ("s1", "s2"):
            if tag in states:
                d = states[tag]
                figs[tag] = (q5(tag, d), d["s"])
        if figs:
            q5_pngs(figs)

    if "q7" in phases and "s1" in states:
        base = q7(states["s1"])   # the x1 re-solve doubles as the Q6 base
        if "q6" in phases:
            q6(states["s1"], base)

    _write_summary()
    print(f"\nV5 IBL-floor diagnosis done in "
          f"{time.perf_counter() - t_all:.0f}s: {len(SUMMARY)} RECORDED "
          "rows (no pass/fail bands)", flush=True)


if __name__ == "__main__":
    main()
